grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      random_state: 0
    search_param_grid:
      penalty: 
      - l2
      C: 
      - 2.5
      - 3.7
      solver: 
      - liblinear 
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params: 
      random_state: 0
    search_param_grid:
      n_estimators: 
      - 150 
      max_depth: 
      - 6 
      max_features: 
      - 5
      - 6 
  # module_2:
  #   class: DecisionTreeClassifier
  #   module: sklearn.tree
  #   params:
  #     random_state: 0 
  #   search_param_grid:
  #     criterion: 
  #     - gini
  #     - entropy
  #     max_depth:
  #     - 7
  #     - 10
  #     min_samples_split:
  #     - 2
  #     - 5
  #     max_features:
  #     - 9
  #     - 7
  # module_3:
  #   class: SVC
  #   module: sklearn.svm
  #   params:
  #     random_state: 0
  #   search_param_grid:
  #     kernel: 
  #     - linear
  #     - rbf 
  #     C:
  #     - 0.1
  #     - 1.0
  #     - 3
  #     gamma:
  #     - scale
  #     - auto

# Best Model
# model_object=RandomForestClassifier(max_depth=6, max_features=5, n_estimators=150, random_state=0), 
# train_f1_score=0.6927405189741125, test_f1_score=0.6734439344304128, train_accuracy=0.828125, test_accuracy=0.818, model_accuracy=0.8230313615308679
